// File generated by Antigravity based on provided Firebase Web configuration.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxcqV4gAfA0sjADw153hD4LNLDuvvdS6M',
    appId: '1:389586444254:web:7832d390574858d552474f',
    messagingSenderId: '389586444254',
    projectId: 'diarynote-fa32a',
    authDomain: 'diarynote-fa32a.firebaseapp.com',
    storageBucket: 'diarynote-fa32a.firebasestorage.app',
    measurementId: 'G-Y788CSBPZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk-POg2vaVjUms3E8MgLS-laH7qyE4i88',
    appId: '1:389586444254:android:657ade107aa7038e52474f',
    messagingSenderId: '389586444254',
    projectId: 'diarynote-fa32a',
    storageBucket: 'diarynote-fa32a.firebasestorage.app',
  );
}
